// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: runner/v1/messages.proto

package runnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunnerStatus int32

const (
	RunnerStatus_RUNNER_STATUS_UNSPECIFIED RunnerStatus = 0
	RunnerStatus_RUNNER_STATUS_IDLE        RunnerStatus = 1
	RunnerStatus_RUNNER_STATUS_ACTIVE      RunnerStatus = 2
	RunnerStatus_RUNNER_STATUS_OFFLINE     RunnerStatus = 3
)

// Enum value maps for RunnerStatus.
var (
	RunnerStatus_name = map[int32]string{
		0: "RUNNER_STATUS_UNSPECIFIED",
		1: "RUNNER_STATUS_IDLE",
		2: "RUNNER_STATUS_ACTIVE",
		3: "RUNNER_STATUS_OFFLINE",
	}
	RunnerStatus_value = map[string]int32{
		"RUNNER_STATUS_UNSPECIFIED": 0,
		"RUNNER_STATUS_IDLE":        1,
		"RUNNER_STATUS_ACTIVE":      2,
		"RUNNER_STATUS_OFFLINE":     3,
	}
)

func (x RunnerStatus) Enum() *RunnerStatus {
	p := new(RunnerStatus)
	*p = x
	return p
}

func (x RunnerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunnerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_v1_messages_proto_enumTypes[0].Descriptor()
}

func (RunnerStatus) Type() protoreflect.EnumType {
	return &file_runner_v1_messages_proto_enumTypes[0]
}

func (x RunnerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunnerStatus.Descriptor instead.
func (RunnerStatus) EnumDescriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{0}
}

type Result int32

const (
	Result_RESULT_UNSPECIFIED Result = 0
	Result_RESULT_SUCCESS     Result = 1
	Result_RESULT_FAILURE     Result = 2
	Result_RESULT_CANCELLED   Result = 3
	Result_RESULT_SKIPPED     Result = 4
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "RESULT_SUCCESS",
		2: "RESULT_FAILURE",
		3: "RESULT_CANCELLED",
		4: "RESULT_SKIPPED",
	}
	Result_value = map[string]int32{
		"RESULT_UNSPECIFIED": 0,
		"RESULT_SUCCESS":     1,
		"RESULT_FAILURE":     2,
		"RESULT_CANCELLED":   3,
		"RESULT_SKIPPED":     4,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_v1_messages_proto_enumTypes[1].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_runner_v1_messages_proto_enumTypes[1]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{1}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Token string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Deprecated: Marked as deprecated in runner/v1/messages.proto.
	AgentLabels []string `protobuf:"bytes,3,rep,name=agent_labels,json=agentLabels,proto3" json:"agent_labels,omitempty"`
	// Deprecated: Marked as deprecated in runner/v1/messages.proto.
	CustomLabels  []string `protobuf:"bytes,4,rep,name=custom_labels,json=customLabels,proto3" json:"custom_labels,omitempty"`
	Version       string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Labels        []string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	Ephemeral     bool     `protobuf:"varint,7,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	Capabilities  []string `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_runner_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Deprecated: Marked as deprecated in runner/v1/messages.proto.
func (x *RegisterRequest) GetAgentLabels() []string {
	if x != nil {
		return x.AgentLabels
	}
	return nil
}

// Deprecated: Marked as deprecated in runner/v1/messages.proto.
func (x *RegisterRequest) GetCustomLabels() []string {
	if x != nil {
		return x.CustomLabels
	}
	return nil
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runner        *Runner                `protobuf:"bytes,1,opt,name=runner,proto3" json:"runner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_runner_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetRunner() *Runner {
	if x != nil {
		return x.Runner
	}
	return nil
}

type DeclareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareRequest) Reset() {
	*x = DeclareRequest{}
	mi := &file_runner_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareRequest) ProtoMessage() {}

func (x *DeclareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareRequest.ProtoReflect.Descriptor instead.
func (*DeclareRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DeclareRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeclareRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DeclareRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type DeclareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runner        *Runner                `protobuf:"bytes,1,opt,name=runner,proto3" json:"runner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareResponse) Reset() {
	*x = DeclareResponse{}
	mi := &file_runner_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareResponse) ProtoMessage() {}

func (x *DeclareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareResponse.ProtoReflect.Descriptor instead.
func (*DeclareResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *DeclareResponse) GetRunner() *Runner {
	if x != nil {
		return x.Runner
	}
	return nil
}

type FetchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TasksVersion  int64                  `protobuf:"varint,1,opt,name=tasks_version,json=tasksVersion,proto3" json:"tasks_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTaskRequest) Reset() {
	*x = FetchTaskRequest{}
	mi := &file_runner_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTaskRequest) ProtoMessage() {}

func (x *FetchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTaskRequest.ProtoReflect.Descriptor instead.
func (*FetchTaskRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *FetchTaskRequest) GetTasksVersion() int64 {
	if x != nil {
		return x.TasksVersion
	}
	return 0
}

type FetchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	TasksVersion  int64                  `protobuf:"varint,2,opt,name=tasks_version,json=tasksVersion,proto3" json:"tasks_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTaskResponse) Reset() {
	*x = FetchTaskResponse{}
	mi := &file_runner_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTaskResponse) ProtoMessage() {}

func (x *FetchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTaskResponse.ProtoReflect.Descriptor instead.
func (*FetchTaskResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *FetchTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *FetchTaskResponse) GetTasksVersion() int64 {
	if x != nil {
		return x.TasksVersion
	}
	return 0
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *TaskState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Outputs       map[string]string      `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_runner_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTaskRequest) GetState() *TaskState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *UpdateTaskRequest) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *TaskState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	SentOutputs   []string               `protobuf:"bytes,2,rep,name=sent_outputs,json=sentOutputs,proto3" json:"sent_outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_runner_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTaskResponse) GetState() *TaskState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *UpdateTaskResponse) GetSentOutputs() []string {
	if x != nil {
		return x.SentOutputs
	}
	return nil
}

type UpdateLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Index         int64                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Rows          []*LogRow              `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	NoMore        bool                   `protobuf:"varint,4,opt,name=no_more,json=noMore,proto3" json:"no_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLogRequest) Reset() {
	*x = UpdateLogRequest{}
	mi := &file_runner_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLogRequest) ProtoMessage() {}

func (x *UpdateLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLogRequest.ProtoReflect.Descriptor instead.
func (*UpdateLogRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLogRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *UpdateLogRequest) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *UpdateLogRequest) GetRows() []*LogRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *UpdateLogRequest) GetNoMore() bool {
	if x != nil {
		return x.NoMore
	}
	return false
}

type UpdateLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckIndex      int64                  `protobuf:"varint,1,opt,name=ack_index,json=ackIndex,proto3" json:"ack_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLogResponse) Reset() {
	*x = UpdateLogResponse{}
	mi := &file_runner_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLogResponse) ProtoMessage() {}

func (x *UpdateLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLogResponse.ProtoReflect.Descriptor instead.
func (*UpdateLogResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateLogResponse) GetAckIndex() int64 {
	if x != nil {
		return x.AckIndex
	}
	return 0
}

type Runner struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid   string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Token  string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Name   string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Status RunnerStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=runner.v1.RunnerStatus" json:"status,omitempty"`
	// Deprecated: Marked as deprecated in runner/v1/messages.proto.
	AgentLabels []string `protobuf:"bytes,6,rep,name=agent_labels,json=agentLabels,proto3" json:"agent_labels,omitempty"`
	// Deprecated: Marked as deprecated in runner/v1/messages.proto.
	CustomLabels  []string `protobuf:"bytes,7,rep,name=custom_labels,json=customLabels,proto3" json:"custom_labels,omitempty"`
	Version       string   `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	Labels        []string `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty"`
	Ephemeral     bool     `protobuf:"varint,10,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runner) Reset() {
	*x = Runner{}
	mi := &file_runner_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runner) ProtoMessage() {}

func (x *Runner) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runner.ProtoReflect.Descriptor instead.
func (*Runner) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *Runner) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Runner) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Runner) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Runner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Runner) GetStatus() RunnerStatus {
	if x != nil {
		return x.Status
	}
	return RunnerStatus_RUNNER_STATUS_UNSPECIFIED
}

// Deprecated: Marked as deprecated in runner/v1/messages.proto.
func (x *Runner) GetAgentLabels() []string {
	if x != nil {
		return x.AgentLabels
	}
	return nil
}

// Deprecated: Marked as deprecated in runner/v1/messages.proto.
func (x *Runner) GetCustomLabels() []string {
	if x != nil {
		return x.CustomLabels
	}
	return nil
}

func (x *Runner) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Runner) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Runner) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

type Task struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowPayload []byte                 `protobuf:"bytes,2,opt,name=workflow_payload,json=workflowPayload,proto3,oneof" json:"workflow_payload,omitempty"`
	Context         *structpb.Struct       `protobuf:"bytes,3,opt,name=context,proto3,oneof" json:"context,omitempty"`
	Secrets         map[string]string      `protobuf:"bytes,4,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated: Marked as deprecated in runner/v1/messages.proto.
	Machine       string               `protobuf:"bytes,5,opt,name=machine,proto3" json:"machine,omitempty"`
	Needs         map[string]*TaskNeed `protobuf:"bytes,6,rep,name=needs,proto3" json:"needs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Vars          map[string]string    `protobuf:"bytes,7,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_runner_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetWorkflowPayload() []byte {
	if x != nil {
		return x.WorkflowPayload
	}
	return nil
}

func (x *Task) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Task) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// Deprecated: Marked as deprecated in runner/v1/messages.proto.
func (x *Task) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *Task) GetNeeds() map[string]*TaskNeed {
	if x != nil {
		return x.Needs
	}
	return nil
}

func (x *Task) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type TaskNeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       map[string]string      `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Result        Result                 `protobuf:"varint,2,opt,name=result,proto3,enum=runner.v1.Result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskNeed) Reset() {
	*x = TaskNeed{}
	mi := &file_runner_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskNeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskNeed) ProtoMessage() {}

func (x *TaskNeed) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskNeed.ProtoReflect.Descriptor instead.
func (*TaskNeed) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *TaskNeed) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TaskNeed) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_UNSPECIFIED
}

type TaskState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        Result                 `protobuf:"varint,2,opt,name=result,proto3,enum=runner.v1.Result" json:"result,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	StoppedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	Steps         []*StepState           `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskState) Reset() {
	*x = TaskState{}
	mi := &file_runner_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskState) ProtoMessage() {}

func (x *TaskState) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskState.ProtoReflect.Descriptor instead.
func (*TaskState) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *TaskState) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskState) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_UNSPECIFIED
}

func (x *TaskState) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TaskState) GetStoppedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StoppedAt
	}
	return nil
}

func (x *TaskState) GetSteps() []*StepState {
	if x != nil {
		return x.Steps
	}
	return nil
}

type StepState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        Result                 `protobuf:"varint,2,opt,name=result,proto3,enum=runner.v1.Result" json:"result,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	StoppedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	LogIndex      int64                  `protobuf:"varint,5,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	LogLength     int64                  `protobuf:"varint,6,opt,name=log_length,json=logLength,proto3" json:"log_length,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepState) Reset() {
	*x = StepState{}
	mi := &file_runner_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepState) ProtoMessage() {}

func (x *StepState) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepState.ProtoReflect.Descriptor instead.
func (*StepState) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *StepState) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StepState) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_UNSPECIFIED
}

func (x *StepState) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StepState) GetStoppedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StoppedAt
	}
	return nil
}

func (x *StepState) GetLogIndex() int64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *StepState) GetLogLength() int64 {
	if x != nil {
		return x.LogLength
	}
	return 0
}

func (x *StepState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LogRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRow) Reset() {
	*x = LogRow{}
	mi := &file_runner_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRow) ProtoMessage() {}

func (x *LogRow) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRow.ProtoReflect.Descriptor instead.
func (*LogRow) Descriptor() ([]byte, []int) {
	return file_runner_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *LogRow) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *LogRow) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_runner_v1_messages_proto protoreflect.FileDescriptor

const file_runner_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x18runner/v1/messages.proto\x12\trunner.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x01\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12%\n" +
	"\fagent_labels\x18\x03 \x03(\tB\x02\x18\x01R\vagentLabels\x12'\n" +
	"\rcustom_labels\x18\x04 \x03(\tB\x02\x18\x01R\fcustomLabels\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x16\n" +
	"\x06labels\x18\x06 \x03(\tR\x06labels\x12\x1c\n" +
	"\tephemeral\x18\a \x01(\bR\tephemeral\x12\"\n" +
	"\fcapabilities\x18\b \x03(\tR\fcapabilities\"=\n" +
	"\x10RegisterResponse\x12)\n" +
	"\x06runner\x18\x01 \x01(\v2\x11.runner.v1.RunnerR\x06runner\"f\n" +
	"\x0eDeclareRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"<\n" +
	"\x0fDeclareResponse\x12)\n" +
	"\x06runner\x18\x01 \x01(\v2\x11.runner.v1.RunnerR\x06runner\"7\n" +
	"\x10FetchTaskRequest\x12#\n" +
	"\rtasks_version\x18\x01 \x01(\x03R\ftasksVersion\"]\n" +
	"\x11FetchTaskResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.runner.v1.TaskR\x04task\x12#\n" +
	"\rtasks_version\x18\x02 \x01(\x03R\ftasksVersion\"\xc0\x01\n" +
	"\x11UpdateTaskRequest\x12*\n" +
	"\x05state\x18\x01 \x01(\v2\x14.runner.v1.TaskStateR\x05state\x12C\n" +
	"\aoutputs\x18\x02 \x03(\v2).runner.v1.UpdateTaskRequest.OutputsEntryR\aoutputs\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x12UpdateTaskResponse\x12*\n" +
	"\x05state\x18\x01 \x01(\v2\x14.runner.v1.TaskStateR\x05state\x12!\n" +
	"\fsent_outputs\x18\x02 \x03(\tR\vsentOutputs\"\x81\x01\n" +
	"\x10UpdateLogRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x03R\x05index\x12%\n" +
	"\x04rows\x18\x03 \x03(\v2\x11.runner.v1.LogRowR\x04rows\x12\x17\n" +
	"\ano_more\x18\x04 \x01(\bR\x06noMore\"0\n" +
	"\x11UpdateLogResponse\x12\x1b\n" +
	"\tack_index\x18\x01 \x01(\x03R\backIndex\"\xa7\x02\n" +
	"\x06Runner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.runner.v1.RunnerStatusR\x06status\x12%\n" +
	"\fagent_labels\x18\x06 \x03(\tB\x02\x18\x01R\vagentLabels\x12'\n" +
	"\rcustom_labels\x18\a \x03(\tB\x02\x18\x01R\fcustomLabels\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12\x16\n" +
	"\x06labels\x18\t \x03(\tR\x06labels\x12\x1c\n" +
	"\tephemeral\x18\n" +
	" \x01(\bR\tephemeral\"\x9a\x04\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x10workflow_payload\x18\x02 \x01(\fH\x00R\x0fworkflowPayload\x88\x01\x01\x126\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\acontext\x88\x01\x01\x126\n" +
	"\asecrets\x18\x04 \x03(\v2\x1c.runner.v1.Task.SecretsEntryR\asecrets\x12\x1c\n" +
	"\amachine\x18\x05 \x01(\tB\x02\x18\x01R\amachine\x120\n" +
	"\x05needs\x18\x06 \x03(\v2\x1a.runner.v1.Task.NeedsEntryR\x05needs\x12-\n" +
	"\x04vars\x18\a \x03(\v2\x19.runner.v1.Task.VarsEntryR\x04vars\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aM\n" +
	"\n" +
	"NeedsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.runner.v1.TaskNeedR\x05value:\x028\x01\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x13\n" +
	"\x11_workflow_payloadB\n" +
	"\n" +
	"\b_context\"\xad\x01\n" +
	"\bTaskNeed\x12:\n" +
	"\aoutputs\x18\x01 \x03(\v2 .runner.v1.TaskNeed.OutputsEntryR\aoutputs\x12)\n" +
	"\x06result\x18\x02 \x01(\x0e2\x11.runner.v1.ResultR\x06result\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\tTaskState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12)\n" +
	"\x06result\x18\x02 \x01(\x0e2\x11.runner.v1.ResultR\x06result\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"stopped_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstoppedAt\x12*\n" +
	"\x05steps\x18\x05 \x03(\v2\x14.runner.v1.StepStateR\x05steps\"\x8c\x02\n" +
	"\tStepState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12)\n" +
	"\x06result\x18\x02 \x01(\x0e2\x11.runner.v1.ResultR\x06result\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"stopped_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstoppedAt\x12\x1b\n" +
	"\tlog_index\x18\x05 \x01(\x03R\blogIndex\x12\x1d\n" +
	"\n" +
	"log_length\x18\x06 \x01(\x03R\tlogLength\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\"R\n" +
	"\x06LogRow\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent*z\n" +
	"\fRunnerStatus\x12\x1d\n" +
	"\x19RUNNER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RUNNER_STATUS_IDLE\x10\x01\x12\x18\n" +
	"\x14RUNNER_STATUS_ACTIVE\x10\x02\x12\x19\n" +
	"\x15RUNNER_STATUS_OFFLINE\x10\x03*r\n" +
	"\x06Result\x12\x16\n" +
	"\x12RESULT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRESULT_SUCCESS\x10\x01\x12\x12\n" +
	"\x0eRESULT_FAILURE\x10\x02\x12\x14\n" +
	"\x10RESULT_CANCELLED\x10\x03\x12\x12\n" +
	"\x0eRESULT_SKIPPED\x10\x04B\x92\x01\n" +
	"\rcom.runner.v1B\rMessagesProtoP\x01Z-gitea.dev/actions-proto-go/runner/v1;runnerv1\xa2\x02\x03RXX\xaa\x02\tRunner.V1\xca\x02\tRunner\\V1\xe2\x02\x15Runner\\V1\\GPBMetadata\xea\x02\n" +
	"Runner::V1b\x06proto3"

var (
	file_runner_v1_messages_proto_rawDescOnce sync.Once
	file_runner_v1_messages_proto_rawDescData []byte
)

func file_runner_v1_messages_proto_rawDescGZIP() []byte {
	file_runner_v1_messages_proto_rawDescOnce.Do(func() {
		file_runner_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_v1_messages_proto_rawDesc), len(file_runner_v1_messages_proto_rawDesc)))
	})
	return file_runner_v1_messages_proto_rawDescData
}

var file_runner_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runner_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_runner_v1_messages_proto_goTypes = []any{
	(RunnerStatus)(0),             // 0: runner.v1.RunnerStatus
	(Result)(0),                   // 1: runner.v1.Result
	(*RegisterRequest)(nil),       // 2: runner.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 3: runner.v1.RegisterResponse
	(*DeclareRequest)(nil),        // 4: runner.v1.DeclareRequest
	(*DeclareResponse)(nil),       // 5: runner.v1.DeclareResponse
	(*FetchTaskRequest)(nil),      // 6: runner.v1.FetchTaskRequest
	(*FetchTaskResponse)(nil),     // 7: runner.v1.FetchTaskResponse
	(*UpdateTaskRequest)(nil),     // 8: runner.v1.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),    // 9: runner.v1.UpdateTaskResponse
	(*UpdateLogRequest)(nil),      // 10: runner.v1.UpdateLogRequest
	(*UpdateLogResponse)(nil),     // 11: runner.v1.UpdateLogResponse
	(*Runner)(nil),                // 12: runner.v1.Runner
	(*Task)(nil),                  // 13: runner.v1.Task
	(*TaskNeed)(nil),              // 14: runner.v1.TaskNeed
	(*TaskState)(nil),             // 15: runner.v1.TaskState
	(*StepState)(nil),             // 16: runner.v1.StepState
	(*LogRow)(nil),                // 17: runner.v1.LogRow
	nil,                           // 18: runner.v1.UpdateTaskRequest.OutputsEntry
	nil,                           // 19: runner.v1.Task.SecretsEntry
	nil,                           // 20: runner.v1.Task.NeedsEntry
	nil,                           // 21: runner.v1.Task.VarsEntry
	nil,                           // 22: runner.v1.TaskNeed.OutputsEntry
	(*structpb.Struct)(nil),       // 23: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
}
var file_runner_v1_messages_proto_depIdxs = []int32{
	12, // 0: runner.v1.RegisterResponse.runner:type_name -> runner.v1.Runner
	12, // 1: runner.v1.DeclareResponse.runner:type_name -> runner.v1.Runner
	13, // 2: runner.v1.FetchTaskResponse.task:type_name -> runner.v1.Task
	15, // 3: runner.v1.UpdateTaskRequest.state:type_name -> runner.v1.TaskState
	18, // 4: runner.v1.UpdateTaskRequest.outputs:type_name -> runner.v1.UpdateTaskRequest.OutputsEntry
	15, // 5: runner.v1.UpdateTaskResponse.state:type_name -> runner.v1.TaskState
	17, // 6: runner.v1.UpdateLogRequest.rows:type_name -> runner.v1.LogRow
	0,  // 7: runner.v1.Runner.status:type_name -> runner.v1.RunnerStatus
	23, // 8: runner.v1.Task.context:type_name -> google.protobuf.Struct
	19, // 9: runner.v1.Task.secrets:type_name -> runner.v1.Task.SecretsEntry
	20, // 10: runner.v1.Task.needs:type_name -> runner.v1.Task.NeedsEntry
	21, // 11: runner.v1.Task.vars:type_name -> runner.v1.Task.VarsEntry
	22, // 12: runner.v1.TaskNeed.outputs:type_name -> runner.v1.TaskNeed.OutputsEntry
	1,  // 13: runner.v1.TaskNeed.result:type_name -> runner.v1.Result
	1,  // 14: runner.v1.TaskState.result:type_name -> runner.v1.Result
	24, // 15: runner.v1.TaskState.started_at:type_name -> google.protobuf.Timestamp
	24, // 16: runner.v1.TaskState.stopped_at:type_name -> google.protobuf.Timestamp
	16, // 17: runner.v1.TaskState.steps:type_name -> runner.v1.StepState
	1,  // 18: runner.v1.StepState.result:type_name -> runner.v1.Result
	24, // 19: runner.v1.StepState.started_at:type_name -> google.protobuf.Timestamp
	24, // 20: runner.v1.StepState.stopped_at:type_name -> google.protobuf.Timestamp
	24, // 21: runner.v1.LogRow.time:type_name -> google.protobuf.Timestamp
	14, // 22: runner.v1.Task.NeedsEntry.value:type_name -> runner.v1.TaskNeed
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_runner_v1_messages_proto_init() }
func file_runner_v1_messages_proto_init() {
	if File_runner_v1_messages_proto != nil {
		return
	}
	file_runner_v1_messages_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_v1_messages_proto_rawDesc), len(file_runner_v1_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runner_v1_messages_proto_goTypes,
		DependencyIndexes: file_runner_v1_messages_proto_depIdxs,
		EnumInfos:         file_runner_v1_messages_proto_enumTypes,
		MessageInfos:      file_runner_v1_messages_proto_msgTypes,
	}.Build()
	File_runner_v1_messages_proto = out.File
	file_runner_v1_messages_proto_goTypes = nil
	file_runner_v1_messages_proto_depIdxs = nil
}
